### ISSUE TITLE
Content Security Policy issue with plugin for Gatsby

### ISSUE THREAD

**Issue by lfergon** [tmttn/gatsby-plugin-linkedin-insight#4]
## What?
![Screenshot from 2022-03-16 21-17-52](https://user-images.githubusercontent.com/1398298/158683193-4016213b-8fde-4aee-8e1e-dab216a62b6d.png)

Once published the page, content security policy does not allow to load the inline script of the plugin, we are using [gatsby-plugin-csp](https://www.gatsbyjs.com/plugins/gatsby-plugin-csp/) and the csp:

`
"script-src":
            "'self' 'unsafe-inline' 'report-sample' https://snap.licdn.com https://snap.licdn.com/li.lms-analytics/insight.min.js ",
...
 `

**Comment by tmttn** [comment]
@lfergon as this plugin adds LinkedIn analytics, you would have to allow connections to LinkedIn tracking URL's in the CSP plugin.
